set(ESP32_HID_TOOLS_DIR "${CMAKE_SOURCE_DIR}/submodules/esp32-hid-tools")

if(EXISTS "${ESP32_HID_TOOLS_DIR}/CMakeLists.txt")
  set(HAS_ESP32_HID_TOOLS ON)
  message(STATUS "ESP32 HID Tools: Found at ${ESP32_HID_TOOLS_DIR}")
  add_subdirectory(${ESP32_HID_TOOLS_DIR} ${CMAKE_BINARY_DIR}/submodules/esp32-hid-tools)
  include_directories(${ESP32_HID_TOOLS_DIR})
else()
  set(HAS_ESP32_HID_TOOLS OFF)
  message(STATUS "ESP32 HID Tools: Submodule not found at ${ESP32_HID_TOOLS_DIR}, disabling.")
endif()
